// Code generated by spdx-gen. DO NOT EDIT.

package spdx

import (
	"time"
)

// AIPackage Specifies an AI package and its associated information.
type AIPackage struct {
	IsoAutomationLevel              *IsoAutomationLevel       `json:"isoAutomationLevel,omitempty"`
	AutonomyType                    *PresenceType             `json:"autonomyType,omitempty"`
	Domain                          []string                  `json:"domain,omitempty"`
	EnergyConsumption               *EnergyConsumption        `json:"energyConsumption,omitempty"`
	Hyperparameter                  []DictionaryEntry         `json:"hyperparameter,omitempty"`
	InformationAboutApplication     string                    `json:"informationAboutApplication,omitempty"`
	InformationAboutTraining        string                    `json:"informationAboutTraining,omitempty"`
	Limitation                      string                    `json:"limitation,omitempty"`
	Metric                          []DictionaryEntry         `json:"metric,omitempty"`
	MetricDecisionThreshold         []DictionaryEntry         `json:"metricDecisionThreshold,omitempty"`
	ModelDataPreprocessing          []string                  `json:"modelDataPreprocessing,omitempty"`
	ModelExplainability             []string                  `json:"modelExplainability,omitempty"`
	SafetyRiskAssessment            *SafetyRiskAssessmentType `json:"safetyRiskAssessment,omitempty"`
	StandardCompliance              []string                  `json:"standardCompliance,omitempty"`
	TypeOfModel                     []string                  `json:"typeOfModel,omitempty"`
	UseSensitivePersonalInformation *PresenceType             `json:"useSensitivePersonalInformation,omitempty"`
}

// Action Class that describes an action that has occurred.
// Action is an abstract type and should not be instantiated directly.
type Action struct {
	ActionStartTime       time.Time         `json:"actionStartTime,omitempty"`
	ActionEndTime         time.Time         `json:"actionEndTime,omitempty"`
	ActionLocation        []Location        `json:"actionLocation,omitempty"`
	AdditionalInformation []DictionaryEntry `json:"additionalInformation,omitempty"`
}

// Agent Agent represents anything with the potential to act on a system.
type Agent struct {
}

// Annotation An assertion made in relation to one or more elements.
type Annotation struct {
	AnnotationType AnnotationType `json:"annotationType" validate:"required"`
	ContentType    string         `json:"contentType,omitempty"`
	Statement      string         `json:"statement,omitempty"`
	Subject        Element        `json:"subject" validate:"required"`
}

// AnnotationType Specifies the type of an annotation.
type AnnotationType struct {
}

// AnyLicenseInfo Abstract class representing a license combination consisting of one or more licenses.
type AnyLicenseInfo struct {
}

// Artifact A distinct article or unit within the domain.
// Artifact is an abstract type and should not be instantiated directly.
type Artifact struct {
	OriginatedBy   []Agent       `json:"originatedBy,omitempty"`
	SuppliedBy     *Agent        `json:"suppliedBy,omitempty"`
	BuiltTime      time.Time     `json:"builtTime,omitempty"`
	ReleaseTime    time.Time     `json:"releaseTime,omitempty"`
	ValidUntilTime time.Time     `json:"validUntilTime,omitempty"`
	StandardName   []string      `json:"standardName,omitempty"`
	SupportLevel   []SupportType `json:"supportLevel,omitempty"`
	IntendedUse    string        `json:"intendedUse,omitempty"`
}

// AssemblyAction AssemblyAction represents the event of creating a product by assembling individual components.
type AssemblyAction struct {
}

// AssemblyProcess The AssemblyProcess represents the process of creating a product by assembling a set of components, potentially in a way that allows for at disassembly (at least partially).
type AssemblyProcess struct {
}

// AuthenticationProtocolType Protocols which support authentication.
type AuthenticationProtocolType struct {
}

// Bom A container for a grouping of SPDX 3 content characterizing details (provenance, composition, licensing, etc.) about a product.
type Bom struct {
}

// BoundaryCrossingAction An action of crossing a boundary is defined in this class.
type BoundaryCrossingAction struct {
}

// BoundaryDefinitionAction The boundary definition is used to define boundaries.
type BoundaryDefinitionAction struct {
	BoundaryParameter []DictionaryEntry `json:"boundaryParameter" validate:"required"`
}

// BoundaryDefinitionProcess The Boundary Definition Process refers to the process class used to produce boundaries.
type BoundaryDefinitionProcess struct {
}

// Build Class that describes a build instance of software/artifacts.
type Build struct {
	BuildType              string            `json:"buildType" validate:"required,omitempty,url"`
	BuildId                string            `json:"buildId,omitempty"`
	ConfigSourceEntrypoint []string          `json:"configSourceEntrypoint,omitempty"`
	ConfigSourceUri        []string          `json:"configSourceUri,omitempty" validate:"omitempty,url"`
	ConfigSourceDigest     []Hash            `json:"configSourceDigest,omitempty"`
	Parameter              []DictionaryEntry `json:"parameter,omitempty"`
	BuildStartTime         time.Time         `json:"buildStartTime,omitempty"`
	BuildEndTime           time.Time         `json:"buildEndTime,omitempty"`
	Environment            []DictionaryEntry `json:"environment,omitempty"`
}

// BulkHardware Products or commodities produced as a bulk unit are called bulk products. Commodities are often sold in bulk.
type BulkHardware struct {
	BulkQuantity UnitOfMeasure `json:"bulkQuantity" validate:"required"`
}

// Bundle A collection of Elements that have a shared context.
type Bundle struct {
	Context string `json:"context,omitempty"`
}

// CdxPropertiesExtension A type of extension consisting of a list of name value pairs.
type CdxPropertiesExtension struct {
	CdxProperty []CdxPropertyEntry `json:"cdxProperty" validate:"required"`
}

// CdxPropertyEntry A property name with an associated value.
type CdxPropertyEntry struct {
	CdxPropName  string `json:"cdxPropName" validate:"required"`
	CdxPropValue string `json:"cdxPropValue,omitempty"`
}

// ChangeAction An actual change to a product.
type ChangeAction struct {
}

// ChangeProcess A prescribed change to a product.
type ChangeProcess struct {
}

// ConfidentialityLevelType Categories of confidentiality level.
type ConfidentialityLevelType struct {
}

// ConjunctiveLicenseSet Portion of an AnyLicenseInfo representing a set of licensing information where all elements apply.
type ConjunctiveLicenseSet struct {
	Member []AnyLicenseInfo `json:"member" validate:"required,min=2"`
}

// ContactPointRelationship A contact point from an Artifact to an Agent.
type ContactPointRelationship struct {
	ContactType ContactPointRelationshipType `json:"contactType" validate:"required"`
}

// ContactPointRelationshipType Information about the type of contact point for `ContactPointRelationship`s.
type ContactPointRelationshipType struct {
}

// ContentIdentifier A canonical, unique, immutable identifier.
type ContentIdentifier struct {
	ContentIdentifierType  ContentIdentifierType `json:"contentIdentifierType" validate:"required"`
	ContentIdentifierValue string                `json:"contentIdentifierValue" validate:"required,omitempty,url"`
}

// ContentIdentifierType Specifies the type of a content identifier.
type ContentIdentifierType struct {
}

// CreateAction CreationAction represents an event of product creation.
type CreateAction struct {
}

// CreateProcess The CreateProcess refers to the abstract process class that can be used to represent the process of creation of a product.
type CreateProcess struct {
}

// CreationInfo Provides information about the creation of the Element.
type CreationInfo struct {
	SpecVersion  string    `json:"specVersion" validate:"required"`
	Comment      string    `json:"comment,omitempty"`
	Created      time.Time `json:"created" validate:"required"`
	CreatedBy    []Agent   `json:"createdBy" validate:"required"`
	CreatedUsing []Tool    `json:"createdUsing,omitempty"`
}

// CustomLicense A license that is not listed on the SPDX License List.
type CustomLicense struct {
}

// CustomLicenseAddition A license addition that is not listed on the SPDX Exceptions List.
type CustomLicenseAddition struct {
}

// CvssSeverityType Specifies the CVSS base, temporal, threat, or environmental severity type.
type CvssSeverityType struct {
}

// CvssV2VulnAssessmentRelationship Provides a CVSS version 2.0 assessment for a vulnerability.
type CvssV2VulnAssessmentRelationship struct {
	Score        float64 `json:"score" validate:"required"`
	VectorString string  `json:"vectorString" validate:"required"`
}

// CvssV3VulnAssessmentRelationship Provides a CVSS version 3 assessment for a vulnerability.
type CvssV3VulnAssessmentRelationship struct {
	Score        float64          `json:"score" validate:"required"`
	Severity     CvssSeverityType `json:"severity" validate:"required"`
	VectorString string           `json:"vectorString" validate:"required"`
}

// CvssV4VulnAssessmentRelationship Provides a CVSS version 4 assessment for a vulnerability.
type CvssV4VulnAssessmentRelationship struct {
	Score        float64          `json:"score" validate:"required"`
	Severity     CvssSeverityType `json:"severity" validate:"required"`
	VectorString string           `json:"vectorString" validate:"required"`
}

// DatasetAvailabilityType Availability of dataset.
type DatasetAvailabilityType struct {
}

// DatasetPackage Specifies a data package and its associated information.
type DatasetPackage struct {
	InLanguage                      []string                  `json:"inLanguage,omitempty"`
	AnonymizationMethodUsed         []string                  `json:"anonymizationMethodUsed,omitempty"`
	ConfidentialityLevel            *ConfidentialityLevelType `json:"confidentialityLevel,omitempty"`
	DataCollectionProcess           string                    `json:"dataCollectionProcess,omitempty"`
	DataPreprocessing               []string                  `json:"dataPreprocessing,omitempty"`
	DatasetAvailability             *DatasetAvailabilityType  `json:"datasetAvailability,omitempty"`
	DatasetNoise                    string                    `json:"datasetNoise,omitempty"`
	DatasetSize                     int                       `json:"datasetSize,omitempty"`
	DatasetType                     []DatasetType             `json:"datasetType" validate:"required"`
	DatasetUpdateMechanism          string                    `json:"datasetUpdateMechanism,omitempty"`
	HasSensitivePersonalInformation *PresenceType             `json:"hasSensitivePersonalInformation,omitempty"`
	IntendedUse                     string                    `json:"intendedUse,omitempty"`
	KnownBias                       []string                  `json:"knownBias,omitempty"`
	Sensor                          []DictionaryEntry         `json:"sensor,omitempty"`
}

// DatasetType Enumeration of dataset types.
type DatasetType struct {
}

// DefinedProcess Class that describes a process.
// DefinedProcess is an abstract type and should not be instantiated directly.
type DefinedProcess struct {
	ProcessVersion   string                `json:"processVersion" validate:"required"`
	ProcessRationale string                `json:"processRationale,omitempty"`
	ProcessReadiness *ProcessReadinessType `json:"processReadiness,omitempty"`
}

// DefinedStateProcess This process is used to determine the state of an affected Element.
type DefinedStateProcess struct {
	VaildState []State `json:"vaildState" validate:"required"`
}

// DefinedType The DefinedType class associates a specific type with its defined source.
type DefinedType struct {
	TypeFromSource   string        `json:"typeFromSource" validate:"required"`
	DefinitionSource Specification `json:"definitionSource" validate:"required"`
}

// DestroyAction The record of destruction is entered in this action.
type DestroyAction struct {
	DestructionPerformedBy []Agent `json:"destructionPerformedBy" validate:"required"`
}

// DestroyProcess The destruction process is defined in this process.
type DestroyProcess struct {
}

// DictionaryEntry A key with an associated value.
type DictionaryEntry struct {
	Key   string `json:"key" validate:"required"`
	Value string `json:"value,omitempty"`
}

// Dimensions Dimensions generally refer to measurable extents or attributes that define the size, shape, or scale of an object, system, or concept.
type Dimensions struct {
	XAxisLength MeasureOfLength `json:"xAxisLength" validate:"required"`
	YAxisLength MeasureOfLength `json:"yAxisLength" validate:"required"`
	ZAxisLength MeasureOfLength `json:"zAxisLength" validate:"required"`
}

// DisjunctiveLicenseSet Portion of an AnyLicenseInfo representing a set of licensing information where only one of the elements applies.
type DisjunctiveLicenseSet struct {
	Member []AnyLicenseInfo `json:"member" validate:"required,min=2"`
}

// Element Base domain class from which all other SPDX 3 domain classes derive.
// Element is an abstract type and should not be instantiated directly.
type Element struct {
	SpdxID             string               `json:"spdxId"`
	Name               string               `json:"name,omitempty"`
	Summary            string               `json:"summary,omitempty"`
	Description        string               `json:"description,omitempty"`
	Comment            string               `json:"comment,omitempty"`
	CreationInfo       CreationInfo         `json:"creationInfo" validate:"required"`
	VerifiedUsing      []IntegrityMethod    `json:"verifiedUsing,omitempty"`
	ExternalRef        []ExternalRef        `json:"externalRef,omitempty"`
	ExternalIdentifier []ExternalIdentifier `json:"externalIdentifier,omitempty"`
	Extension          []interface{}        `json:"extension,omitempty"`
}

// ElementCollection A collection of Elements, not necessarily with unifying context.
// ElementCollection is an abstract type and should not be instantiated directly.
type ElementCollection struct {
	Elements           []Element               `json:"element,omitempty"`
	RootElement        []Element               `json:"rootElement,omitempty"`
	ProfileConformance []ProfileIdentifierType `json:"profileConformance,omitempty"`
}

// EnergyConsumption A class for describing the energy consumption incurred by an AI model in different stages of its lifecycle.
type EnergyConsumption struct {
	FinetuningEnergyConsumption []EnergyConsumptionDescription `json:"finetuningEnergyConsumption,omitempty"`
	InferenceEnergyConsumption  []EnergyConsumptionDescription `json:"inferenceEnergyConsumption,omitempty"`
	TrainingEnergyConsumption   []EnergyConsumptionDescription `json:"trainingEnergyConsumption,omitempty"`
}

// EnergyConsumptionDescription The class that helps note down the quantity of energy consumption and the unit used for measurement.
type EnergyConsumptionDescription struct {
	EnergyQuantity float64        `json:"energyQuantity" validate:"required"`
	EnergyUnit     EnergyUnitType `json:"energyUnit" validate:"required"`
}

// EnergyUnitType Specifies the unit of energy consumption.
type EnergyUnitType struct {
}

// EpssVulnAssessmentRelationship Provides an EPSS assessment for a vulnerability.
type EpssVulnAssessmentRelationship struct {
	Probability float64 `json:"probability" validate:"required"`
	Percentile  float64 `json:"percentile" validate:"required"`
}

// ExploitCatalogType Specifies the exploit catalog type.
type ExploitCatalogType struct {
}

// ExploitCatalogVulnAssessmentRelationship Provides an exploit assessment of a vulnerability.
type ExploitCatalogVulnAssessmentRelationship struct {
	CatalogType ExploitCatalogType `json:"catalogType" validate:"required"`
	Exploited   bool               `json:"exploited" validate:"required"`
	Locator     string             `json:"locator" validate:"required,omitempty,url"`
}

// ExtendableLicense Abstract class representing a License or an OrLaterOperator.
type ExtendableLicense struct {
}

// Extension A characterization of some aspect of an Element that is associated with the Element in a generalized fashion.
type Extension struct {
}

// ExternalIdentifier A reference to a resource identifier defined outside the scope of SPDX 3 content that uniquely identifies an Element.
type ExternalIdentifier struct {
	ExternalIdentifierType ExternalIdentifierType `json:"externalIdentifierType" validate:"required"`
	Identifier             string                 `json:"identifier" validate:"required"`
	Comment                string                 `json:"comment,omitempty"`
	IdentifierLocator      []string               `json:"identifierLocator,omitempty" validate:"omitempty,url"`
	IssuingAuthority       string                 `json:"issuingAuthority,omitempty"`
}

// ExternalIdentifierType Specifies the type of an external identifier.
type ExternalIdentifierType struct {
}

// ExternalMap A map of Element identifiers that are used within an SpdxDocument but defined external to that SpdxDocument.
type ExternalMap struct {
	ExternalSpdxId   string            `json:"externalSpdxId" validate:"required,omitempty,url"`
	VerifiedUsing    []IntegrityMethod `json:"verifiedUsing,omitempty"`
	LocationHint     string            `json:"locationHint,omitempty" validate:"omitempty,url"`
	DefiningArtifact *Artifact         `json:"definingArtifact,omitempty"`
}

// ExternalRef A reference to a resource outside the scope of SPDX 3 content related to an Element.
type ExternalRef struct {
	ExternalRefType *ExternalRefType `json:"externalRefType,omitempty"`
	Locator         []string         `json:"locator,omitempty"`
	ContentType     string           `json:"contentType,omitempty"`
	Comment         string           `json:"comment,omitempty"`
}

// ExternalRefType Specifies the type of an external reference.
type ExternalRefType struct {
}

// File Refers to any object that stores content on a computer.
type File struct {
	ContentType string        `json:"contentType,omitempty"`
	FileKind    *FileKindType `json:"fileKind,omitempty"`
}

// FileKindType Enumeration of the different kinds of SPDX file.
type FileKindType struct {
}

// Hardware Class that describes an instance of Hardware.
// Hardware is an abstract type and should not be instantiated directly.
type Hardware struct {
	ProductAgent                       Agent             `json:"productAgent" validate:"required"`
	HardwareVersion                    string            `json:"hardwareVersion,omitempty"`
	PartNumber                         string            `json:"partNumber" validate:"required"`
	ReleaseDate                        time.Time         `json:"releaseDate,omitempty"`
	SerialNumber                       string            `json:"serialNumber,omitempty"`
	BatchNumber                        string            `json:"batchNumber,omitempty"`
	Hazard                             []DefinedType     `json:"hazard,omitempty"`
	Category                           []DefinedType     `json:"category,omitempty"`
	AdditionalInformationSpecification []Specification   `json:"additionalInformationSpecification,omitempty"`
	AdditionalInformation              []DictionaryEntry `json:"additionalInformation,omitempty"`
}

// HarvestAction HarvestAction represents the act of creating a product by directly extracting goods or materials from nature.
type HarvestAction struct {
}

// HarvestProcess Harvest is the process of extracting goods or products from nature.
type HarvestProcess struct {
}

// Hash A mathematically calculated representation of a grouping of data.
type Hash struct {
	Algorithm HashAlgorithm `json:"algorithm" validate:"required"`
	HashValue string        `json:"hashValue" validate:"required"`
}

// HashAlgorithm A mathematical algorithm that maps data of arbitrary size to a bit string.
type HashAlgorithm struct {
}

// IndividualElement A concrete subclass of Element used by Individuals in the Core profile.
type IndividualElement struct {
}

// IndividualLicensingInfo A concrete subclass of AnyLicenseInfo used by Individuals in the ExpandedLicensing profile.
type IndividualLicensingInfo struct {
}

// InspectionAction An inspection action refers to a specific activity or set of activities performed during an inspection to examine, verify, or evaluate an item, process, or system.
type InspectionAction struct {
}

// InspectionProcess Inspection Process defines specific various processes needed to satisfy the inspection requirements for a specific product or service.
type InspectionProcess struct {
	PlannedInspectionLocation []Location `json:"plannedInspectionLocation,omitempty"`
}

// InstantiateVirtualHardwareProcess Class that describes an InstantiateVirtualHardwareProcess that is used to define VirtualHardware and its source.
type InstantiateVirtualHardwareProcess struct {
}

// IntegrityMethod Provides an independently reproducible mechanism that permits verification of a specific Element.
// IntegrityMethod is an abstract type and should not be instantiated directly.
type IntegrityMethod struct {
	Comment string `json:"comment,omitempty"`
}

// IsoAutomationLevel Defines the level of automation a system possesses.
type IsoAutomationLevel struct {
}

// License Abstract class for the portion of an AnyLicenseInfo representing a license.
// License is an abstract type and should not be instantiated directly.
type License struct {
	LicenseText             string   `json:"licenseText" validate:"required"`
	IsDeprecatedLicenseId   bool     `json:"isDeprecatedLicenseId,omitempty"`
	IsFsfLibre              bool     `json:"isFsfLibre,omitempty"`
	IsOsiApproved           bool     `json:"isOsiApproved,omitempty"`
	LicenseXml              string   `json:"licenseXml,omitempty"`
	ObsoletedBy             string   `json:"obsoletedBy,omitempty"`
	SeeAlso                 []string `json:"seeAlso,omitempty" validate:"omitempty,url"`
	StandardLicenseHeader   string   `json:"standardLicenseHeader,omitempty"`
	StandardLicenseTemplate string   `json:"standardLicenseTemplate,omitempty"`
}

// LicenseAddition Abstract class for additional text intended to be added to a License, but which is not itself a standalone License.
// LicenseAddition is an abstract type and should not be instantiated directly.
type LicenseAddition struct {
	AdditionText             string   `json:"additionText" validate:"required"`
	IsDeprecatedAdditionId   bool     `json:"isDeprecatedAdditionId,omitempty"`
	LicenseXml               string   `json:"licenseXml,omitempty"`
	ObsoletedBy              string   `json:"obsoletedBy,omitempty"`
	SeeAlso                  []string `json:"seeAlso,omitempty" validate:"omitempty,url"`
	StandardAdditionTemplate string   `json:"standardAdditionTemplate,omitempty"`
}

// LicenseExpression An SPDX Element containing an SPDX license expression string.
type LicenseExpression struct {
	LicenseExpression  string            `json:"licenseExpression" validate:"required"`
	LicenseListVersion string            `json:"licenseListVersion,omitempty"`
	CustomIdToUri      []DictionaryEntry `json:"customIdToUri,omitempty"`
}

// LifecycleScopeType Provide an enumerated set of lifecycle phases that can provide context to relationships.
type LifecycleScopeType struct {
}

// LifecycleScopedRelationship Provide context for a relationship that occurs in the lifecycle.
type LifecycleScopedRelationship struct {
	Scope *LifecycleScopeType `json:"scope,omitempty"`
}

// ListedLicense A license that is listed on the SPDX License List.
type ListedLicense struct {
	DeprecatedVersion string `json:"deprecatedVersion,omitempty"`
	ListVersionAdded  string `json:"listVersionAdded,omitempty"`
}

// ListedLicenseException A license exception that is listed on the SPDX Exceptions list.
type ListedLicenseException struct {
	DeprecatedVersion string `json:"deprecatedVersion,omitempty"`
	ListVersionAdded  string `json:"listVersionAdded,omitempty"`
}

// Location Location is used to define the location, address or coordinates of a place.
// Location is an abstract type and should not be instantiated directly.
type Location struct {
	LocationTime time.Time `json:"locationTime,omitempty"`
}

// ManufactureAction ManufactureAction represents the act of creating a product by a manufacturing process.
type ManufactureAction struct {
}

// ManufactureProcess This class represents the process involved in manufacturing products.
type ManufactureProcess struct {
}

// MeasureOfLength The measure of length refers to the dimension of an object or space that describes how long it is, typically expressed in various units depending on the system of measurement being used.
type MeasureOfLength struct {
}

// MeasureOfMass The measure of mass refers to the quantity of matter in an object or substance.
type MeasureOfMass struct {
}

// ModifyAction An actual alteration of a product.
type ModifyAction struct {
}

// ModifyProcess A prescribed alteration of a product.
type ModifyProcess struct {
}

// NamespaceMap A mapping between prefixes and namespace partial URIs.
type NamespaceMap struct {
	Prefix    string `json:"prefix" validate:"required"`
	Namespace string `json:"namespace" validate:"required,omitempty,url"`
}

// OrLaterOperator Portion of an AnyLicenseInfo representing this version, or any later version, of the indicated License.
type OrLaterOperator struct {
	SubjectLicense License `json:"subjectLicense" validate:"required"`
}

// Organization A group of people who work together in an organized way for a shared purpose.
type Organization struct {
	HeadquartersLocation []Location `json:"headquartersLocation,omitempty"`
}

// OutOfSpecAction An out of specification action is defined in this class.
type OutOfSpecAction struct {
}

// Package Refers to any unit of content that can be associated with a distribution of software.
type Package struct {
	DownloadLocation string `json:"downloadLocation,omitempty" validate:"omitempty,url"`
	HomePage         string `json:"homePage,omitempty" validate:"omitempty,url"`
	PackageVersion   string `json:"packageVersion,omitempty"`
	PackageUrl       string `json:"packageUrl,omitempty" validate:"omitempty,url"`
	SourceInfo       string `json:"sourceInfo,omitempty"`
}

// PackageVerificationCode An SPDX version 2.X compatible verification method for software packages.
type PackageVerificationCode struct {
	Algorithm                           HashAlgorithm `json:"algorithm" validate:"required"`
	HashValue                           string        `json:"hashValue" validate:"required"`
	PackageVerificationCodeExcludedFile []string      `json:"packageVerificationCodeExcludedFile,omitempty"`
}

// Person An individual human being.
type Person struct {
}

// PhysicalHardware Class that describes a physical instance of Hardware.
type PhysicalHardware struct {
	MassOfHardware *MeasureOfMass `json:"massOfHardware,omitempty"`
	Dimensions     *Dimensions    `json:"dimensions,omitempty"`
	CenterOfMass   *Dimensions    `json:"centerOfMass,omitempty"`
}

// PhysicalLocation A physical location is a tangible, geographically identifiable place where objects, people, or assets exist or operate.
type PhysicalLocation struct {
	Country                 string   `json:"country,omitempty"`
	CountyCode              string   `json:"countyCode,omitempty"`
	City                    string   `json:"city,omitempty"`
	PostalCode              string   `json:"postalCode,omitempty"`
	PostalName              string   `json:"postalName,omitempty"`
	PostOfficeBoxNumber     string   `json:"postOfficeBoxNumber,omitempty"`
	ProvinceStateCode       string   `json:"provinceStateCode,omitempty"`
	StreetAddress           string   `json:"streetAddress,omitempty"`
	GeographicPointLocation []string `json:"geographicPointLocation,omitempty"`
}

// PlanAction A PlanAction involves the execution of a plan in relation to a PlanProcess.
type PlanAction struct {
}

// PlanProcess Process plans outline the stages of implementation or use related to a process.
type PlanProcess struct {
}

// PositiveIntegerRange A tuple of two positive integers that define a range.
type PositiveIntegerRange struct {
	BeginIntegerRange int `json:"beginIntegerRange" validate:"required"`
	EndIntegerRange   int `json:"endIntegerRange" validate:"required"`
}

// PresenceType Categories of presence or absence.
type PresenceType struct {
}

// ProcessReadinessType The ProcessReadinessType is defined by the enumeration.
type ProcessReadinessType struct {
}

// ProductSpecification A product specification (product spec) is a detailed document that outlines the technical, functional, and design requirements of a product.
type ProductSpecification struct {
	Hazard      []DefinedType `json:"hazard,omitempty"`
	PartNumber  []string      `json:"partNumber" validate:"required"`
	ItemVersion []string      `json:"itemVersion,omitempty"`
}

// ProfileIdentifierType Enumeration of the valid profiles.
type ProfileIdentifierType struct {
}

// Regulation Regulation represents a rule or directive maintained by an authority.
type Regulation struct {
}

// Relationship Describes a relationship between one or more elements.
type Relationship struct {
	From             Element                   `json:"from" validate:"required"`
	To               []Element                 `json:"to" validate:"required"`
	RelationshipType RelationshipType          `json:"relationshipType" validate:"required"`
	Completeness     *RelationshipCompleteness `json:"completeness,omitempty"`
	StartTime        time.Time                 `json:"startTime,omitempty"`
	EndTime          time.Time                 `json:"endTime,omitempty"`
}

// RelationshipCompleteness Indicates whether a relationship is known to be complete, incomplete, or if no assertion is made with respect to relationship completeness.
type RelationshipCompleteness struct {
}

// RelationshipType Information about the relationship between two Elements.
type RelationshipType struct {
}

// ReproduceAction Reproduction is the biological process by which organisms generate new individuals of the same species.
type ReproduceAction struct {
}

// ReproduceProcess Reproduction is the biological process by which living organisms produce offspring.
type ReproduceProcess struct {
}

// ResolutionAction Products out of specification require a resolution action. This is the action of resolution.
type ResolutionAction struct {
}

// ResponsibilityChangeAction ResponsibilityChangeAction refers to the transfer of responsibility from one party to another.
type ResponsibilityChangeAction struct {
	Current                 Agent              `json:"current" validate:"required"`
	Previous                *Agent             `json:"previous,omitempty"`
	ResponsibilityChangedOn []Element          `json:"responsibilityChangedOn" validate:"required"`
	ResponsibilityCategory  ResponsibilityType `json:"responsibilityCategory" validate:"required"`
}

// ResponsibilityChangeProcess ResponsibilityChangeProcess refers to the process of transferring responsibility from one party to another.
type ResponsibilityChangeProcess struct {
	PlannedCurrent                       *Agent             `json:"plannedCurrent,omitempty"`
	PlannedPrevious                      *Agent             `json:"plannedPrevious,omitempty"`
	PlannedProductofResponsibilityChange []Element          `json:"plannedProductofResponsibilityChange,omitempty"`
	ResponsibilityCategory               ResponsibilityType `json:"responsibilityCategory" validate:"required"`
}

// ResponsibilityType These categories help define sets Responsibility Type.
type ResponsibilityType struct {
}

// SafetyRiskAssessmentType Specifies the safety risk level.
type SafetyRiskAssessmentType struct {
}

// Sbom A collection of SPDX Elements describing a single package.
type Sbom struct {
	SbomType []SbomType `json:"sbomType,omitempty"`
}

// SbomType Provides a set of values to be used to describe the common types of SBOMs that tools may create.
type SbomType struct {
}

// SimpleLicensingText A license or addition that is not listed on the SPDX License List.
type SimpleLicensingText struct {
	LicenseText string `json:"licenseText" validate:"required"`
}

// Snippet Describes a certain part of a file.
type Snippet struct {
	ByteRange       *PositiveIntegerRange `json:"byteRange,omitempty"`
	LineRange       *PositiveIntegerRange `json:"lineRange,omitempty"`
	SnippetFromFile File                  `json:"snippetFromFile" validate:"required"`
}

// SoftwareAgent A software agent.
type SoftwareAgent struct {
}

// SoftwareArtifact A distinct article or unit related to Software.
// SoftwareArtifact is an abstract type and should not be instantiated directly.
type SoftwareArtifact struct {
	PrimaryPurpose    *SoftwarePurpose    `json:"primaryPurpose,omitempty"`
	AdditionalPurpose []SoftwarePurpose   `json:"additionalPurpose,omitempty"`
	CopyrightText     string              `json:"copyrightText,omitempty"`
	AttributionText   []string            `json:"attributionText,omitempty"`
	ContentIdentifier []ContentIdentifier `json:"contentIdentifier,omitempty"`
	ArtifactSize      int                 `json:"artifactSize,omitempty"`
}

// SoftwarePurpose Provides information about the primary purpose of an Element.
type SoftwarePurpose struct {
}

// SoftwareService Software provided as a service over a network.
type SoftwareService struct {
	Provider                     []Agent                      `json:"provider" validate:"required"`
	ServerAuthenticationProtocol []AuthenticationProtocolType `json:"serverAuthenticationProtocol,omitempty"`
	ServiceHostingCountry        []string                     `json:"serviceHostingCountry,omitempty"`
}

// SpdxDocument A collection of SPDX Elements that could potentially be serialized.
type SpdxDocument struct {
	Import       []ExternalMap   `json:"import,omitempty"`
	NamespaceMap []NamespaceMap  `json:"namespaceMap,omitempty"`
	DataLicense  *AnyLicenseInfo `json:"dataLicense,omitempty"`
}

// Specification A specification is a detailed description of the design, requirements, or features of a product, process, or system.
type Specification struct {
	SpecType *SpecificationType `json:"specType,omitempty"`
}

// SpecificationType A specification type defines the nature of a specification.
type SpecificationType struct {
}

// SsvcDecisionType Specifies the SSVC decision type.
type SsvcDecisionType struct {
}

// SsvcVulnAssessmentRelationship Provides an SSVC assessment for a vulnerability.
type SsvcVulnAssessmentRelationship struct {
	DecisionType SsvcDecisionType `json:"decisionType" validate:"required"`
}

// State A state is an instance that describes what a system, component, subsystem, process, or project has achieved at any given time.
type State struct {
}

// StateAction This is the state of an affected Element at a specific moment in time.
type StateAction struct {
	CurrentState    State               `json:"currentState" validate:"required"`
	DecisionProcess DefinedStateProcess `json:"decisionProcess" validate:"required"`
}

// StorageAction Records the storage of a product.
type StorageAction struct {
}

// StorageProcess Prescribes the storage of a product.
type StorageProcess struct {
	PlannedStorageLocation []Location `json:"plannedStorageLocation,omitempty"`
}

// SupportRelationship Describes how an Agent provides support for an Artifact.
type SupportRelationship struct {
	SupportLevel SupportType `json:"supportLevel" validate:"required"`
}

// SupportType Indicates the type of support that is associated with an artifact.
type SupportType struct {
}

// TestAction A test action is a specific action associated with a test.
type TestAction struct {
}

// TestProcess Test Process defines the testing process for an element.
type TestProcess struct {
}

// Tool An element of hardware and/or software utilized to carry out a particular function.
type Tool struct {
}

// TransportAction An actual change to a product's location.
type TransportAction struct {
	TransportRoute  []string   `json:"transportRoute,omitempty"`
	PickupLocation  []Location `json:"pickupLocation" validate:"required"`
	DropoffLocation []Location `json:"dropoffLocation,omitempty"`
}

// TransportProcess A prescribed change to a product's location.
type TransportProcess struct {
	PlannedTransportRoutes []string   `json:"plannedTransportRoutes,omitempty"`
	ForPickupLocation      []Location `json:"forPickupLocation,omitempty"`
	ForDropoffLocation     []Location `json:"forDropoffLocation,omitempty"`
}

// UnitOfMeasure UnitofMeasure specify information structures through industry standards for Units of Measure, Quantity Kinds, Dimensions and Data Types.
type UnitOfMeasure struct {
	Quantity string `json:"quantity" validate:"required"`
	UnitQUDT string `json:"unitQUDT" validate:"required"`
}

// UseAction The action of product use.
type UseAction struct {
}

// UseProcess Use Process defines actions used by elements.
type UseProcess struct {
}

// VexAffectedVulnAssessmentRelationship Connects a vulnerability and an element designating the element as a product affected by the vulnerability.
type VexAffectedVulnAssessmentRelationship struct {
	ActionStatement     string    `json:"actionStatement" validate:"required"`
	ActionStatementTime time.Time `json:"actionStatementTime,omitempty"`
}

// VexFixedVulnAssessmentRelationship Links a vulnerability and elements representing products (in the VEX sense) where a fix has been applied and are no longer affected.
type VexFixedVulnAssessmentRelationship struct {
}

// VexJustificationType Specifies the VEX justification type.
type VexJustificationType struct {
}

// VexNotAffectedVulnAssessmentRelationship Links a vulnerability and one or more elements designating the latter as products not affected by the vulnerability.
type VexNotAffectedVulnAssessmentRelationship struct {
	JustificationType   *VexJustificationType `json:"justificationType,omitempty"`
	ImpactStatement     string                `json:"impactStatement,omitempty"`
	ImpactStatementTime time.Time             `json:"impactStatementTime,omitempty"`
}

// VexUnderInvestigationVulnAssessmentRelationship Designates elements as products where the impact of a vulnerability is being investigated.
type VexUnderInvestigationVulnAssessmentRelationship struct {
}

// VexVulnAssessmentRelationship Abstract ancestor class for all VEX relationships.
// VexVulnAssessmentRelationship is an abstract type and should not be instantiated directly.
type VexVulnAssessmentRelationship struct {
	VexVersion  string `json:"vexVersion,omitempty"`
	StatusNotes string `json:"statusNotes,omitempty"`
}

// VirtualHardware Class that describes an instance of VirtualHardware.
type VirtualHardware struct {
	VirtualHardwareModel *VirtualHardwareModelType `json:"virtualHardwareModel,omitempty"`
}

// VirtualHardwareModelType VirtualHardwareModelType sets the VirtualHardware Model Type.
type VirtualHardwareModelType struct {
}

// VulnAssessmentRelationship Abstract ancestor class for all vulnerability assessments.
// VulnAssessmentRelationship is an abstract type and should not be instantiated directly.
type VulnAssessmentRelationship struct {
	AssessedElement *SoftwareArtifact `json:"assessedElement,omitempty"`
	PublishedTime   time.Time         `json:"publishedTime,omitempty"`
	SuppliedBy      *Agent            `json:"suppliedBy,omitempty"`
	ModifiedTime    time.Time         `json:"modifiedTime,omitempty"`
	WithdrawnTime   time.Time         `json:"withdrawnTime,omitempty"`
}

// Vulnerability Specifies a vulnerability and its associated information.
type Vulnerability struct {
	PublishedTime time.Time `json:"publishedTime,omitempty"`
	ModifiedTime  time.Time `json:"modifiedTime,omitempty"`
	WithdrawnTime time.Time `json:"withdrawnTime,omitempty"`
}

// WithAdditionOperator Portion of an AnyLicenseInfo representing a License which has additional text applied to it.
type WithAdditionOperator struct {
	SubjectAddition          LicenseAddition   `json:"subjectAddition" validate:"required"`
	SubjectExtendableLicense ExtendableLicense `json:"subjectExtendableLicense" validate:"required"`
}
