// Code generated by spdx-gen. DO NOT EDIT.

package spdx

import (
	"time"
)

// AIPackage Specifies an AI package and its associated information.
type AIPackage struct {
	Package
	AutonomyType                    PresenceType             `json:"autonomyType,omitempty"`
	Domain                          []string                 `json:"domain,omitempty"`
	EnergyConsumption               *EnergyConsumption       `json:"energyConsumption,omitempty"`
	Hyperparameter                  []DictionaryEntry        `json:"hyperparameter,omitempty"`
	InformationAboutApplication     string                   `json:"informationAboutApplication,omitempty"`
	InformationAboutTraining        string                   `json:"informationAboutTraining,omitempty"`
	Limitation                      string                   `json:"limitation,omitempty"`
	Metric                          []DictionaryEntry        `json:"metric,omitempty"`
	MetricDecisionThreshold         []DictionaryEntry        `json:"metricDecisionThreshold,omitempty"`
	ModelDataPreprocessing          []string                 `json:"modelDataPreprocessing,omitempty"`
	ModelExplainability             []string                 `json:"modelExplainability,omitempty"`
	SafetyRiskAssessment            SafetyRiskAssessmentType `json:"safetyRiskAssessment,omitempty"`
	StandardCompliance              []string                 `json:"standardCompliance,omitempty"`
	TypeOfModel                     []string                 `json:"typeOfModel,omitempty"`
	UseSensitivePersonalInformation PresenceType             `json:"useSensitivePersonalInformation,omitempty"`
}

// EnergyConsumption A class for describing the energy consumption incurred by an AI model in different stages of its lifecycle.
type EnergyConsumption struct {
	FinetuningEnergyConsumption []EnergyConsumptionDescription `json:"finetuningEnergyConsumption,omitempty"`
	InferenceEnergyConsumption  []EnergyConsumptionDescription `json:"inferenceEnergyConsumption,omitempty"`
	TrainingEnergyConsumption   []EnergyConsumptionDescription `json:"trainingEnergyConsumption,omitempty"`
}

// EnergyConsumptionDescription The class that helps note down the quantity of energy consumption and the unit used for measurement.
type EnergyConsumptionDescription struct {
	EnergyQuantity float64        `json:"energyQuantity" validate:"required"`
	EnergyUnit     EnergyUnitType `json:"energyUnit" validate:"required"`
}

// Build Class that describes a build instance of software/artifacts.
type Build struct {
	Element
	BuildType              string            `json:"buildType" validate:"required,omitempty,url"`
	BuildId                string            `json:"buildId,omitempty"`
	ConfigSourceEntrypoint []string          `json:"configSourceEntrypoint,omitempty"`
	ConfigSourceUri        []string          `json:"configSourceUri,omitempty" validate:"omitempty,url"`
	ConfigSourceDigest     []Hash            `json:"configSourceDigest,omitempty"`
	Parameter              []DictionaryEntry `json:"parameter,omitempty"`
	BuildStartTime         time.Time         `json:"buildStartTime,omitempty"`
	BuildEndTime           time.Time         `json:"buildEndTime,omitempty"`
	Environment            []DictionaryEntry `json:"environment,omitempty"`
}

// Agent Agent represents anything with the potential to act on a system.
type Agent struct {
	Element
}

// Annotation An assertion made in relation to one or more elements.
type Annotation struct {
	Element
	AnnotationType AnnotationType `json:"annotationType" validate:"required"`
	ContentType    string         `json:"contentType,omitempty"`
	Statement      string         `json:"statement,omitempty"`
	Subject        Element        `json:"subject" validate:"required"`
}

// Artifact A distinct article or unit within the digital domain.
// Artifact is an abstract type and should not be instantiated directly.
type Artifact struct {
	Element
	OriginatedBy   []Agent       `json:"originatedBy,omitempty"`
	SuppliedBy     *Agent        `json:"suppliedBy,omitempty"`
	BuiltTime      time.Time     `json:"builtTime,omitempty"`
	ReleaseTime    time.Time     `json:"releaseTime,omitempty"`
	ValidUntilTime time.Time     `json:"validUntilTime,omitempty"`
	StandardName   []string      `json:"standardName,omitempty"`
	SupportLevel   []SupportType `json:"supportLevel,omitempty"`
}

// Bom A container for a grouping of SPDX-3.0 content characterizing details (provenence, composition, licensing, etc.) about a product.
type Bom struct {
	Bundle
}

// Bundle A collection of Elements that have a shared context.
type Bundle struct {
	ElementCollection
	Context string `json:"context,omitempty"`
}

// CreationInfo Provides information about the creation of the Element.
type CreationInfo struct {
	SpecVersion  string    `json:"specVersion" validate:"required"`
	Comment      string    `json:"comment,omitempty"`
	Created      time.Time `json:"created" validate:"required"`
	CreatedBy    []Agent   `json:"createdBy" validate:"required"`
	CreatedUsing []Tool    `json:"createdUsing,omitempty"`
}

// DictionaryEntry A key with an associated value.
type DictionaryEntry struct {
	Key   string `json:"key" validate:"required"`
	Value string `json:"value,omitempty"`
}

// Element Base domain class from which all other SPDX-3.0 domain classes derive.
// Element is an abstract type and should not be instantiated directly.
type Element struct {
	SpdxID             string               `json:"spdxId"`
	Name               string               `json:"name,omitempty"`
	Summary            string               `json:"summary,omitempty"`
	Description        string               `json:"description,omitempty"`
	Comment            string               `json:"comment,omitempty"`
	CreationInfo       CreationInfo         `json:"creationInfo" validate:"required"`
	VerifiedUsing      []IntegrityMethod    `json:"verifiedUsing,omitempty"`
	ExternalRef        []ExternalRef        `json:"externalRef,omitempty"`
	ExternalIdentifier []ExternalIdentifier `json:"externalIdentifier,omitempty"`
	Extension          []Extension          `json:"extension,omitempty"`
}

// ElementCollection A collection of Elements, not necessarily with unifying context.
// ElementCollection is an abstract type and should not be instantiated directly.
type ElementCollection struct {
	Element
	Elements           []Element               `json:"element,omitempty"`
	RootElement        []Element               `json:"rootElement,omitempty"`
	ProfileConformance []ProfileIdentifierType `json:"profileConformance,omitempty"`
}

// ExternalIdentifier A reference to a resource identifier defined outside the scope of SPDX-3.0 content that uniquely identifies an Element.
type ExternalIdentifier struct {
	ExternalIdentifierType ExternalIdentifierType `json:"externalIdentifierType" validate:"required"`
	Identifier             string                 `json:"identifier" validate:"required"`
	Comment                string                 `json:"comment,omitempty"`
	IdentifierLocator      []string               `json:"identifierLocator,omitempty" validate:"omitempty,url"`
	IssuingAuthority       string                 `json:"issuingAuthority,omitempty"`
}

// ExternalMap A map of Element identifiers that are used within an SpdxDocument but defined external to that SpdxDocument.
type ExternalMap struct {
	ExternalSpdxId   string            `json:"externalSpdxId" validate:"required,omitempty,url"`
	VerifiedUsing    []IntegrityMethod `json:"verifiedUsing,omitempty"`
	LocationHint     string            `json:"locationHint,omitempty" validate:"omitempty,url"`
	DefiningArtifact *Artifact         `json:"definingArtifact,omitempty"`
}

// ExternalRef A reference to a resource outside the scope of SPDX-3.0 content related to an Element.
type ExternalRef struct {
	ExternalRefType ExternalRefType `json:"externalRefType,omitempty"`
	Locator         []string        `json:"locator,omitempty"`
	ContentType     string          `json:"contentType,omitempty"`
	Comment         string          `json:"comment,omitempty"`
}

// Hash A mathematically calculated representation of a grouping of data.
type Hash struct {
	IntegrityMethod
	Algorithm HashAlgorithm `json:"algorithm" validate:"required"`
	HashValue string        `json:"hashValue" validate:"required"`
}

// IndividualElement A concrete subclass of Element used by Individuals in the Core profile.
type IndividualElement struct {
	Element
}

// IntegrityMethod Provides an independently reproducible mechanism that permits verification of a specific Element.
// IntegrityMethod is an abstract type and should not be instantiated directly.
type IntegrityMethod struct {
	Comment string `json:"comment,omitempty"`
}

// LifecycleScopedRelationship Provide context for a relationship that occurs in the lifecycle.
type LifecycleScopedRelationship struct {
	Relationship
	Scope LifecycleScopeType `json:"scope,omitempty"`
}

// NamespaceMap A mapping between prefixes and namespace partial URIs.
type NamespaceMap struct {
	Prefix    string `json:"prefix" validate:"required"`
	Namespace string `json:"namespace" validate:"required,omitempty,url"`
}

// Organization A group of people who work together in an organized way for a shared purpose.
type Organization struct {
	Agent
}

// PackageVerificationCode An SPDX version 2.X compatible verification method for software packages.
type PackageVerificationCode struct {
	IntegrityMethod
	Algorithm                           HashAlgorithm `json:"algorithm" validate:"required"`
	HashValue                           string        `json:"hashValue" validate:"required"`
	PackageVerificationCodeExcludedFile []string      `json:"packageVerificationCodeExcludedFile,omitempty"`
}

// Person An individual human being.
type Person struct {
	Agent
}

// PositiveIntegerRange A tuple of two positive integers that define a range.
type PositiveIntegerRange struct {
	BeginIntegerRange int `json:"beginIntegerRange" validate:"required"`
	EndIntegerRange   int `json:"endIntegerRange" validate:"required"`
}

// Relationship Describes a relationship between one or more elements.
type Relationship struct {
	Element
	From             Element                  `json:"from" validate:"required"`
	To               []Element                `json:"to" validate:"required"`
	RelationshipType RelationshipType         `json:"relationshipType" validate:"required"`
	Completeness     RelationshipCompleteness `json:"completeness,omitempty"`
	StartTime        time.Time                `json:"startTime,omitempty"`
	EndTime          time.Time                `json:"endTime,omitempty"`
}

// SoftwareAgent A software agent.
type SoftwareAgent struct {
	Agent
}

// SpdxDocument A collection of SPDX Elements that could potentially be serialized.
type SpdxDocument struct {
	ElementCollection
	Import       []ExternalMap   `json:"import,omitempty"`
	NamespaceMap []NamespaceMap  `json:"namespaceMap,omitempty"`
	DataLicense  *AnyLicenseInfo `json:"dataLicense,omitempty"`
}

// Tool An element of hardware and/or software utilized to carry out a particular function.
type Tool struct {
	Element
}

// DatasetPackage Specifies a data package and its associated information.
type DatasetPackage struct {
	Package
	AnonymizationMethodUsed         []string                 `json:"anonymizationMethodUsed,omitempty"`
	ConfidentialityLevel            ConfidentialityLevelType `json:"confidentialityLevel,omitempty"`
	DataCollectionProcess           string                   `json:"dataCollectionProcess,omitempty"`
	DataPreprocessing               []string                 `json:"dataPreprocessing,omitempty"`
	DatasetAvailability             DatasetAvailabilityType  `json:"datasetAvailability,omitempty"`
	DatasetNoise                    string                   `json:"datasetNoise,omitempty"`
	DatasetSize                     int                      `json:"datasetSize,omitempty"`
	DatasetType                     []DatasetType            `json:"datasetType" validate:"required"`
	DatasetUpdateMechanism          string                   `json:"datasetUpdateMechanism,omitempty"`
	HasSensitivePersonalInformation PresenceType             `json:"hasSensitivePersonalInformation,omitempty"`
	IntendedUse                     string                   `json:"intendedUse,omitempty"`
	KnownBias                       []string                 `json:"knownBias,omitempty"`
	Sensor                          []DictionaryEntry        `json:"sensor,omitempty"`
}

// ConjunctiveLicenseSet Portion of an AnyLicenseInfo representing a set of licensing information where all elements apply.
type ConjunctiveLicenseSet struct {
	AnyLicenseInfo
	Member []AnyLicenseInfo `json:"member" validate:"required,min=2"`
}

// CustomLicense A license that is not listed on the SPDX License List.
type CustomLicense struct {
	License
}

// CustomLicenseAddition A license addition that is not listed on the SPDX Exceptions List.
type CustomLicenseAddition struct {
	LicenseAddition
}

// DisjunctiveLicenseSet Portion of an AnyLicenseInfo representing a set of licensing information where only one of the elements applies.
type DisjunctiveLicenseSet struct {
	AnyLicenseInfo
	Member []AnyLicenseInfo `json:"member" validate:"required,min=2"`
}

// ExtendableLicense Abstract class representing a License or an OrLaterOperator.
type ExtendableLicense struct {
	AnyLicenseInfo
}

// IndividualLicensingInfo A concrete subclass of AnyLicenseInfo used by Individuals in the ExpandedLicensing profile.
type IndividualLicensingInfo struct {
	AnyLicenseInfo
}

// License Abstract class for the portion of an AnyLicenseInfo representing a license.
// License is an abstract type and should not be instantiated directly.
type License struct {
	ExtendableLicense
	LicenseText             string   `json:"licenseText" validate:"required"`
	IsDeprecatedLicenseId   bool     `json:"isDeprecatedLicenseId,omitempty"`
	IsFsfLibre              bool     `json:"isFsfLibre,omitempty"`
	IsOsiApproved           bool     `json:"isOsiApproved,omitempty"`
	LicenseXml              string   `json:"licenseXml,omitempty"`
	ObsoletedBy             string   `json:"obsoletedBy,omitempty"`
	SeeAlso                 []string `json:"seeAlso,omitempty" validate:"omitempty,url"`
	StandardLicenseHeader   string   `json:"standardLicenseHeader,omitempty"`
	StandardLicenseTemplate string   `json:"standardLicenseTemplate,omitempty"`
}

// LicenseAddition Abstract class for additional text intended to be added to a License, but which is not itself a standalone License.
// LicenseAddition is an abstract type and should not be instantiated directly.
type LicenseAddition struct {
	Element
	AdditionText             string   `json:"additionText" validate:"required"`
	IsDeprecatedAdditionId   bool     `json:"isDeprecatedAdditionId,omitempty"`
	LicenseXml               string   `json:"licenseXml,omitempty"`
	ObsoletedBy              string   `json:"obsoletedBy,omitempty"`
	SeeAlso                  []string `json:"seeAlso,omitempty" validate:"omitempty,url"`
	StandardAdditionTemplate string   `json:"standardAdditionTemplate,omitempty"`
}

// ListedLicense A license that is listed on the SPDX License List.
type ListedLicense struct {
	License
	DeprecatedVersion string `json:"deprecatedVersion,omitempty"`
	ListVersionAdded  string `json:"listVersionAdded,omitempty"`
}

// ListedLicenseException A license exception that is listed on the SPDX Exceptions list.
type ListedLicenseException struct {
	LicenseAddition
	DeprecatedVersion string `json:"deprecatedVersion,omitempty"`
	ListVersionAdded  string `json:"listVersionAdded,omitempty"`
}

// OrLaterOperator Portion of an AnyLicenseInfo representing this version, or any later version, of the indicated License.
type OrLaterOperator struct {
	ExtendableLicense
	SubjectLicense License `json:"subjectLicense" validate:"required"`
}

// WithAdditionOperator Portion of an AnyLicenseInfo representing a License which has additional text applied to it.
type WithAdditionOperator struct {
	AnyLicenseInfo
	SubjectAddition          LicenseAddition   `json:"subjectAddition" validate:"required"`
	SubjectExtendableLicense ExtendableLicense `json:"subjectExtendableLicense" validate:"required"`
}

// CdxPropertiesExtension A type of extension consisting of a list of name value pairs.
type CdxPropertiesExtension struct {
	Extension
	CdxProperty []CdxPropertyEntry `json:"cdxProperty" validate:"required"`
}

// CdxPropertyEntry A property name with an associated value.
type CdxPropertyEntry struct {
	CdxPropName  string `json:"cdxPropName" validate:"required"`
	CdxPropValue string `json:"cdxPropValue,omitempty"`
}

// Extension A characterization of some aspect of an Element that is associated with the Element in a generalized fashion.
type Extension struct {
}

// CvssV2VulnAssessmentRelationship Provides a CVSS version 2.0 assessment for a vulnerability.
type CvssV2VulnAssessmentRelationship struct {
	VulnAssessmentRelationship
	Score        float64 `json:"score" validate:"required"`
	VectorString string  `json:"vectorString" validate:"required"`
}

// CvssV3VulnAssessmentRelationship Provides a CVSS version 3 assessment for a vulnerability.
type CvssV3VulnAssessmentRelationship struct {
	VulnAssessmentRelationship
	Score        float64          `json:"score" validate:"required"`
	Severity     CvssSeverityType `json:"severity" validate:"required"`
	VectorString string           `json:"vectorString" validate:"required"`
}

// CvssV4VulnAssessmentRelationship Provides a CVSS version 4 assessment for a vulnerability.
type CvssV4VulnAssessmentRelationship struct {
	VulnAssessmentRelationship
	Score        float64          `json:"score" validate:"required"`
	Severity     CvssSeverityType `json:"severity" validate:"required"`
	VectorString string           `json:"vectorString" validate:"required"`
}

// EpssVulnAssessmentRelationship Provides an EPSS assessment for a vulnerability.
type EpssVulnAssessmentRelationship struct {
	VulnAssessmentRelationship
	Probability float64 `json:"probability" validate:"required"`
	Percentile  float64 `json:"percentile" validate:"required"`
}

// ExploitCatalogVulnAssessmentRelationship Provides an exploit assessment of a vulnerability.
type ExploitCatalogVulnAssessmentRelationship struct {
	VulnAssessmentRelationship
	CatalogType ExploitCatalogType `json:"catalogType" validate:"required"`
	Exploited   bool               `json:"exploited" validate:"required"`
	Locator     string             `json:"locator" validate:"required,omitempty,url"`
}

// SsvcVulnAssessmentRelationship Provides an SSVC assessment for a vulnerability.
type SsvcVulnAssessmentRelationship struct {
	VulnAssessmentRelationship
	DecisionType SsvcDecisionType `json:"decisionType" validate:"required"`
}

// VexAffectedVulnAssessmentRelationship Connects a vulnerability and an element designating the element as a product affected by the vulnerability.
type VexAffectedVulnAssessmentRelationship struct {
	VexVulnAssessmentRelationship
	ActionStatement     string    `json:"actionStatement" validate:"required"`
	ActionStatementTime time.Time `json:"actionStatementTime,omitempty"`
}

// VexFixedVulnAssessmentRelationship Links a vulnerability and elements representing products (in the VEX sense) where a fix has been applied and are no longer affected.
type VexFixedVulnAssessmentRelationship struct {
	VexVulnAssessmentRelationship
}

// VexNotAffectedVulnAssessmentRelationship Links a vulnerability and one or more elements designating the latter as products not affected by the vulnerability.
type VexNotAffectedVulnAssessmentRelationship struct {
	VexVulnAssessmentRelationship
	JustificationType   VexJustificationType `json:"justificationType,omitempty"`
	ImpactStatement     string               `json:"impactStatement,omitempty"`
	ImpactStatementTime time.Time            `json:"impactStatementTime,omitempty"`
}

// VexUnderInvestigationVulnAssessmentRelationship Designates elements as products where the impact of a vulnerability is being investigated.
type VexUnderInvestigationVulnAssessmentRelationship struct {
	VexVulnAssessmentRelationship
}

// VexVulnAssessmentRelationship Abstract ancestor class for all VEX relationships
// VexVulnAssessmentRelationship is an abstract type and should not be instantiated directly.
type VexVulnAssessmentRelationship struct {
	VulnAssessmentRelationship
	VexVersion  string `json:"vexVersion,omitempty"`
	StatusNotes string `json:"statusNotes,omitempty"`
}

// VulnAssessmentRelationship Abstract ancestor class for all vulnerability assessments
// VulnAssessmentRelationship is an abstract type and should not be instantiated directly.
type VulnAssessmentRelationship struct {
	Relationship
	AssessedElement *SoftwareArtifact `json:"assessedElement,omitempty"`
	PublishedTime   time.Time         `json:"publishedTime,omitempty"`
	SuppliedBy      *Agent            `json:"suppliedBy,omitempty"`
	ModifiedTime    time.Time         `json:"modifiedTime,omitempty"`
	WithdrawnTime   time.Time         `json:"withdrawnTime,omitempty"`
}

// Vulnerability Specifies a vulnerability and its associated information.
type Vulnerability struct {
	Artifact
	PublishedTime time.Time `json:"publishedTime,omitempty"`
	ModifiedTime  time.Time `json:"modifiedTime,omitempty"`
	WithdrawnTime time.Time `json:"withdrawnTime,omitempty"`
}

// AnyLicenseInfo Abstract class representing a license combination consisting of one or more licenses.
type AnyLicenseInfo struct {
	Element
}

// LicenseExpression An SPDX Element containing an SPDX license expression string.
type LicenseExpression struct {
	AnyLicenseInfo
	LicenseExpression  string            `json:"licenseExpression" validate:"required"`
	LicenseListVersion string            `json:"licenseListVersion,omitempty"`
	CustomIdToUri      []DictionaryEntry `json:"customIdToUri,omitempty"`
}

// SimpleLicensingText A license or addition that is not listed on the SPDX License List.
type SimpleLicensingText struct {
	Element
	LicenseText string `json:"licenseText" validate:"required"`
}

// ContentIdentifier A canonical, unique, immutable identifier
type ContentIdentifier struct {
	IntegrityMethod
	ContentIdentifierType  ContentIdentifierType `json:"contentIdentifierType" validate:"required"`
	ContentIdentifierValue string                `json:"contentIdentifierValue" validate:"required,omitempty,url"`
}

// File Refers to any object that stores content on a computer.
type File struct {
	SoftwareArtifact
	ContentType string       `json:"contentType,omitempty"`
	FileKind    FileKindType `json:"fileKind,omitempty"`
}

// Package Refers to any unit of content that can be associated with a distribution of software.
type Package struct {
	SoftwareArtifact
	DownloadLocation string `json:"downloadLocation,omitempty" validate:"omitempty,url"`
	HomePage         string `json:"homePage,omitempty" validate:"omitempty,url"`
	PackageVersion   string `json:"packageVersion,omitempty"`
	PackageUrl       string `json:"packageUrl,omitempty" validate:"omitempty,url"`
	SourceInfo       string `json:"sourceInfo,omitempty"`
}

// Sbom A collection of SPDX Elements describing a single package.
type Sbom struct {
	Bom
	SbomType []SbomType `json:"sbomType,omitempty"`
}

// Snippet Describes a certain part of a file.
type Snippet struct {
	SoftwareArtifact
	ByteRange       *PositiveIntegerRange `json:"byteRange,omitempty"`
	LineRange       *PositiveIntegerRange `json:"lineRange,omitempty"`
	SnippetFromFile File                  `json:"snippetFromFile" validate:"required"`
}

// SoftwareArtifact A distinct article or unit related to Software.
// SoftwareArtifact is an abstract type and should not be instantiated directly.
type SoftwareArtifact struct {
	Artifact
	PrimaryPurpose    SoftwarePurpose     `json:"primaryPurpose,omitempty"`
	AdditionalPurpose []SoftwarePurpose   `json:"additionalPurpose,omitempty"`
	CopyrightText     string              `json:"copyrightText,omitempty"`
	AttributionText   []string            `json:"attributionText,omitempty"`
	ContentIdentifier []ContentIdentifier `json:"contentIdentifier,omitempty"`
}
